/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;
import Controllers.FogaoController;
import Controllers.GeladeiraController;
import Controllers.MaquinaController;
import java.awt.Image;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 *
 * @author Mateus Bernini
 */
public class ViewPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ViewPrincipal
     */
    public ViewPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/Imagem/background.png"));
        Image image = icon.getImage();
        Desktop = new javax.swing.JDesktopPane(){

            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemCadastrar = new javax.swing.JMenuItem();
        itemEditar = new javax.swing.JMenuItem();
        itemBuscar = new javax.swing.JMenuItem();
        itemListar = new javax.swing.JMenuItem();
        itemExcluir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        cadGeladeira = new javax.swing.JMenuItem();
        editGeladeira = new javax.swing.JMenuItem();
        buscGeladeira = new javax.swing.JMenuItem();
        tabelaGeladeira = new javax.swing.JMenuItem();
        excluirGeladeiras = new javax.swing.JMenuItem();
        dU = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        cadMáquina = new javax.swing.JMenuItem();
        editMaquinas = new javax.swing.JMenuItem();
        buscMaquina = new javax.swing.JMenuItem();
        tblMaquinas = new javax.swing.JMenuItem();
        exclMaquinas = new javax.swing.JMenuItem();
        maqDicas = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        cadFogao = new javax.swing.JMenuItem();
        editFogao = new javax.swing.JMenuItem();
        buscFogao = new javax.swing.JMenuItem();
        tblFogao = new javax.swing.JMenuItem();
        excFogao = new javax.swing.JMenuItem();
        FogDicas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Desktop.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 777, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 546, Short.MAX_VALUE)
        );

        jMenu1.setText("Peças");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        itemCadastrar.setText("Cadastrar Peças");
        itemCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCadastrarActionPerformed(evt);
            }
        });
        jMenu1.add(itemCadastrar);

        itemEditar.setText("Alterar Peças");
        itemEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEditarActionPerformed(evt);
            }
        });
        jMenu1.add(itemEditar);

        itemBuscar.setText("Buscar Peças");
        itemBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBuscarActionPerformed(evt);
            }
        });
        jMenu1.add(itemBuscar);

        itemListar.setText("Tabela de Peças");
        itemListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemListarActionPerformed(evt);
            }
        });
        jMenu1.add(itemListar);

        itemExcluir.setText("Excluir Peças");
        itemExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemExcluirActionPerformed(evt);
            }
        });
        jMenu1.add(itemExcluir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Geladeiras");

        cadGeladeira.setText("Cadastrar Geladeiras");
        cadGeladeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadGeladeiraActionPerformed(evt);
            }
        });
        jMenu2.add(cadGeladeira);

        editGeladeira.setText("Alterar Geladeiras");
        editGeladeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editGeladeiraActionPerformed(evt);
            }
        });
        jMenu2.add(editGeladeira);

        buscGeladeira.setText("Buscar Geladeiras");
        buscGeladeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscGeladeiraActionPerformed(evt);
            }
        });
        jMenu2.add(buscGeladeira);

        tabelaGeladeira.setText("Tabela de Geladeiras");
        tabelaGeladeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabelaGeladeiraActionPerformed(evt);
            }
        });
        jMenu2.add(tabelaGeladeira);

        excluirGeladeiras.setText("Excluir Geladeiras");
        excluirGeladeiras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirGeladeirasActionPerformed(evt);
            }
        });
        jMenu2.add(excluirGeladeiras);

        dU.setText("Dicas de Uso");
        dU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dUActionPerformed(evt);
            }
        });
        jMenu2.add(dU);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Máquinas de Lavar");

        cadMáquina.setText("Cadastrar Máquinas");
        cadMáquina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadMáquinaActionPerformed(evt);
            }
        });
        jMenu3.add(cadMáquina);

        editMaquinas.setText("Alterar Máquinas");
        editMaquinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editMaquinasActionPerformed(evt);
            }
        });
        jMenu3.add(editMaquinas);

        buscMaquina.setText("Buscar Máquinas");
        buscMaquina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscMaquinaActionPerformed(evt);
            }
        });
        jMenu3.add(buscMaquina);

        tblMaquinas.setText("Tabela de Máquinas");
        tblMaquinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblMaquinasActionPerformed(evt);
            }
        });
        jMenu3.add(tblMaquinas);

        exclMaquinas.setText("Excluir Máquinas");
        exclMaquinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exclMaquinasActionPerformed(evt);
            }
        });
        jMenu3.add(exclMaquinas);

        maqDicas.setText("Dicas de Uso");
        maqDicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maqDicasActionPerformed(evt);
            }
        });
        jMenu3.add(maqDicas);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Fogões");

        cadFogao.setText("Cadastrar Fogões");
        cadFogao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadFogaoActionPerformed(evt);
            }
        });
        jMenu4.add(cadFogao);

        editFogao.setText("Alterar Fogões");
        editFogao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editFogaoActionPerformed(evt);
            }
        });
        jMenu4.add(editFogao);

        buscFogao.setText("Buscar Fogões");
        buscFogao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscFogaoActionPerformed(evt);
            }
        });
        jMenu4.add(buscFogao);

        tblFogao.setText("Tabela de Fogões");
        tblFogao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblFogaoActionPerformed(evt);
            }
        });
        jMenu4.add(tblFogao);

        excFogao.setText("Excluir Fogões");
        excFogao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excFogaoActionPerformed(evt);
            }
        });
        jMenu4.add(excFogao);

        FogDicas.setText("Dicas de Uso");
        FogDicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FogDicasActionPerformed(evt);
            }
        });
        jMenu4.add(FogDicas);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCadastrarActionPerformed
        Views.Pecas.Cadastro cadastro = new Views.Pecas.Cadastro();
        cadastro.setVisible(true);
        Desktop.add(cadastro);
    }//GEN-LAST:event_itemCadastrarActionPerformed

    private void itemEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEditarActionPerformed
        Views.Pecas.Editar editar = new Views.Pecas.Editar();
        editar.setVisible(true);
        Desktop.add(editar);
    }//GEN-LAST:event_itemEditarActionPerformed

    private void itemBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBuscarActionPerformed
        Views.Pecas.Buscar buscar = new Views.Pecas.Buscar();
        buscar.setVisible(true);
        Desktop.add(buscar);
    }//GEN-LAST:event_itemBuscarActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void itemListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemListarActionPerformed
        Views.Pecas.TabelaPecas tabelapc = new Views.Pecas.TabelaPecas();
        tabelapc.setVisible(true);
        Desktop.add(tabelapc);
    }//GEN-LAST:event_itemListarActionPerformed

    private void itemExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemExcluirActionPerformed
        Views.Pecas.Excluir excluir = new Views.Pecas.Excluir();
        excluir.setVisible(true);
        Desktop.add(excluir);
    }//GEN-LAST:event_itemExcluirActionPerformed

    private void cadGeladeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadGeladeiraActionPerformed
        Views.Geladeira.Cadastro cad = new Views.Geladeira.Cadastro();
        cad.setVisible(true);
        Desktop.add(cad);
    }//GEN-LAST:event_cadGeladeiraActionPerformed

    private void editGeladeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editGeladeiraActionPerformed
        Views.Geladeira.Editar edit = new Views.Geladeira.Editar();
        edit.setVisible(true);
        Desktop.add(edit);
    }//GEN-LAST:event_editGeladeiraActionPerformed

    private void buscGeladeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscGeladeiraActionPerformed
        Views.Geladeira.Buscar busc = new Views.Geladeira.Buscar();
        busc.setVisible(true);
        Desktop.add(busc);
    }//GEN-LAST:event_buscGeladeiraActionPerformed

    private void tabelaGeladeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabelaGeladeiraActionPerformed
        Views.Geladeira.TabelaGeladeiras tblcompleta = new Views.Geladeira.TabelaGeladeiras();
        tblcompleta.setVisible(true);
        Desktop.add(tblcompleta);
    }//GEN-LAST:event_tabelaGeladeiraActionPerformed

    private void excluirGeladeirasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirGeladeirasActionPerformed
        Views.Geladeira.Excluir excluir = new Views.Geladeira.Excluir();
        excluir.setVisible(true);
        Desktop.add(excluir);
    }//GEN-LAST:event_excluirGeladeirasActionPerformed

    private void cadMáquinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadMáquinaActionPerformed
        Views.MaquinaLavar.Cadastro cad = new Views.MaquinaLavar.Cadastro();
        cad.setVisible(true);
        Desktop.add(cad);
    }//GEN-LAST:event_cadMáquinaActionPerformed

    private void editMaquinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editMaquinasActionPerformed
        Views.MaquinaLavar.Editar edit = new Views.MaquinaLavar.Editar();
        edit.setVisible(true);
        Desktop.add(edit);
    }//GEN-LAST:event_editMaquinasActionPerformed

    private void buscMaquinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscMaquinaActionPerformed
        Views.MaquinaLavar.Buscar busca = new Views.MaquinaLavar.Buscar();
        busca.setVisible(true);
        Desktop.add(busca);
    }//GEN-LAST:event_buscMaquinaActionPerformed

    private void tblMaquinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblMaquinasActionPerformed
        Views.MaquinaLavar.TabelaMaquinas tabela = new Views.MaquinaLavar.TabelaMaquinas();
        tabela.setVisible(true);
        Desktop.add(tabela);
    }//GEN-LAST:event_tblMaquinasActionPerformed

    private void exclMaquinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exclMaquinasActionPerformed
        Views.MaquinaLavar.Excluir excluir = new Views.MaquinaLavar.Excluir();
        excluir.setVisible(true);
        Desktop.add(excluir);
    }//GEN-LAST:event_exclMaquinasActionPerformed

    private void cadFogaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadFogaoActionPerformed
        Views.Fogao.Cadastro cad = new Views.Fogao.Cadastro();
        cad.setVisible(true);
        Desktop.add(cad);
    }//GEN-LAST:event_cadFogaoActionPerformed

    private void editFogaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editFogaoActionPerformed
        Views.Fogao.Editar edit = new Views.Fogao.Editar();
        edit.setVisible(true);
        Desktop.add(edit);
    }//GEN-LAST:event_editFogaoActionPerformed

    private void buscFogaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscFogaoActionPerformed
        Views.Fogao.Buscar busc = new Views.Fogao.Buscar();
        busc.setVisible(true);
        Desktop.add(busc);
    }//GEN-LAST:event_buscFogaoActionPerformed

    private void tblFogaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblFogaoActionPerformed
        Views.Fogao.TabelaFogoes tbl = new Views.Fogao.TabelaFogoes();
        tbl.setVisible(true);
        Desktop.add(tbl);        
    }//GEN-LAST:event_tblFogaoActionPerformed

    private void excFogaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excFogaoActionPerformed
        Views.Fogao.Excluir excluir = new Views.Fogao.Excluir();
        excluir.setVisible(true);
        Desktop.add(excluir);
    }//GEN-LAST:event_excFogaoActionPerformed

    private void dUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dUActionPerformed
        new GeladeiraController().dicas();
    }//GEN-LAST:event_dUActionPerformed

    private void maqDicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maqDicasActionPerformed
        new MaquinaController().dicas();
    }//GEN-LAST:event_maqDicasActionPerformed

    private void FogDicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FogDicasActionPerformed
        new FogaoController().dicas();
    }//GEN-LAST:event_FogDicasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenuItem FogDicas;
    private javax.swing.JMenuItem buscFogao;
    private javax.swing.JMenuItem buscGeladeira;
    private javax.swing.JMenuItem buscMaquina;
    private javax.swing.JMenuItem cadFogao;
    private javax.swing.JMenuItem cadGeladeira;
    private javax.swing.JMenuItem cadMáquina;
    private javax.swing.JMenuItem dU;
    private javax.swing.JMenuItem editFogao;
    private javax.swing.JMenuItem editGeladeira;
    private javax.swing.JMenuItem editMaquinas;
    private javax.swing.JMenuItem excFogao;
    private javax.swing.JMenuItem exclMaquinas;
    private javax.swing.JMenuItem excluirGeladeiras;
    private javax.swing.JMenuItem itemBuscar;
    private javax.swing.JMenuItem itemCadastrar;
    private javax.swing.JMenuItem itemEditar;
    private javax.swing.JMenuItem itemExcluir;
    private javax.swing.JMenuItem itemListar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem maqDicas;
    private javax.swing.JMenuItem tabelaGeladeira;
    private javax.swing.JMenuItem tblFogao;
    private javax.swing.JMenuItem tblMaquinas;
    // End of variables declaration//GEN-END:variables
}
