/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.MaquinaLavar;

import Controllers.IdInexistenteException;
import Controllers.MaquinaController;
import Controllers.ValorNuloException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Mateus Bernini
 */
public class Buscar extends javax.swing.JInternalFrame {

    int id;

    /**
     * Creates new form Buscar
     */
    public Buscar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMaquinas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtBuscaMarca = new javax.swing.JTextField();
        txtBuscaModelo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtQuantidade = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        txtKgs = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        checkDesconto = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtDesconto = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        tblMaquinas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Marca", "Modelo", "Quantidade", "Valor", "Capacidade(Kgs)", "Desconto"
            }
        ));
        tblMaquinas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMaquinasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMaquinas);

        jLabel1.setText("Buscar pela Marca:");

        jLabel2.setText("Buscar pelo Modelo:");

        txtBuscaMarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscaMarcaKeyReleased(evt);
            }
        });

        txtBuscaModelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscaModeloKeyReleased(evt);
            }
        });

        jLabel3.setText("Item Selecionado:");

        jLabel4.setText("Id:");

        jLabel5.setText("Marca:");

        jLabel6.setText("Modelo:");

        jLabel7.setText("Quantidade:");

        jLabel8.setText("Valor:");

        jLabel9.setText("Capacidade(Kgs):");

        txtId.setEditable(false);

        txtValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValorKeyReleased(evt);
            }
        });

        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setText("EXCLUIR");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnCadastrar.setText("CADASTRAR");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        checkDesconto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desconto 15%", "Desconto 30%", "Desconto 50%" }));

        jLabel10.setText("Desconto:");

        txtDesconto.setEditable(false);

        jLabel11.setText("Selecione o Desconto:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Buscar Máquinas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBuscaMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBuscaModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMarca)
                            .addComponent(txtModelo, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addComponent(txtQuantidade))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCadastrar)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(124, 124, 124))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap()))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtKgs, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                .addComponent(txtValor, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(txtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBuscaMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscaModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(btnEditar)
                        .addGap(30, 30, 30)
                        .addComponent(btnExcluir)
                        .addGap(38, 38, 38)
                        .addComponent(btnCadastrar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtKgs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscaMarcaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaMarcaKeyReleased
        String busca = txtBuscaMarca.getText();
        tblMaquinas.setModel(new MaquinaController().maquinaMarca(busca));
    }//GEN-LAST:event_txtBuscaMarcaKeyReleased

    private void txtBuscaModeloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaModeloKeyReleased
        String busca = txtBuscaModelo.getText();
        tblMaquinas.setModel(new MaquinaController().maquinaModelo(busca));
    }//GEN-LAST:event_txtBuscaModeloKeyReleased

    private void tblMaquinasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMaquinasMouseClicked
        int linha = tblMaquinas.getSelectedRow();
        id = Integer.valueOf(tblMaquinas.getModel().getValueAt(linha, 0).toString());
        txtId.setText(tblMaquinas.getModel().getValueAt(linha, 0).toString());
        txtMarca.setText(tblMaquinas.getModel().getValueAt(linha, 1).toString());
        txtModelo.setText(tblMaquinas.getModel().getValueAt(linha, 2).toString());
        txtQuantidade.setText(tblMaquinas.getModel().getValueAt(linha, 3).toString());
        txtValor.setText(tblMaquinas.getModel().getValueAt(linha, 4).toString());
        txtKgs.setText(tblMaquinas.getModel().getValueAt(linha, 5).toString());
    }//GEN-LAST:event_tblMaquinasMouseClicked

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        try {
            String q = txtQuantidade.getText().replace(",", ".");
            String v = txtValor.getText().replace(",", ".");
            String kgs = txtKgs.getText().replace(",", ".");
            if (new MaquinaController().edit(txtMarca.getText(), txtModelo.getText(), Double.valueOf(q), Double.valueOf(v), Double.valueOf(kgs), Double.valueOf(txtDesconto.getText()), Integer.valueOf(txtId.getText()))) {
                JOptionPane.showMessageDialog(this, "Informações editadas !!");
            }
        } catch (IdInexistenteException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            System.out.println("Erro ocorrido:" + e);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Não é permitido campos vazios !!\n Preencha todos os campos para editar !!");
            System.out.println("Erro ocorrido:" + e);
        } catch (ValorNuloException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            System.out.println("Eroo ocorrido:" + e);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        try {
            if (new MaquinaController().delete(Integer.valueOf(txtId.getText()))) {
                JOptionPane.showMessageDialog(this, "Dados da Máquina de Lavar excluídos !!");
                txtId.setText(null);
                txtMarca.setText(null);
                txtModelo.setText(null);
                txtQuantidade.setText(null);
                txtValor.setText(null);
                txtKgs.setText(null);
            }

        } catch (IdInexistenteException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            System.out.println("Erro ocorrido:" + e);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Campo id vazio e/ou Inexistente !!\nDigite o Id que deseja Excluir !!");
            System.out.println("Erro ocorrido:" + e);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        try {
            MaquinaController mc = new MaquinaController();
            String q = txtQuantidade.getText().replace(",", ".");
            String v = txtValor.getText().replace(",", ".");
            String kgs = txtKgs.getText().replace(",", ".");
            if (mc.create(txtMarca.getText(), txtModelo.getText(), Double.valueOf(q), Double.valueOf(v), Double.valueOf(kgs), Double.valueOf(txtDesconto.getText()))) {
                JOptionPane.showMessageDialog(this, "Dados da Máquina cadastrados!!");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Falha ao cadastrar !!\n" + "Não é permitido campos em vazio !! " + "\nNão é permitido Caracteres em valor e quantidade !!");
            System.out.println(e);
        } catch (ValorNuloException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            System.out.println("Erro ocorrido:" + e);
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void txtValorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorKeyReleased
        try{
        if( checkDesconto.getSelectedIndex() == 0){
            MaquinaController mc = new MaquinaController();     
            txtDesconto.setText(String.valueOf(mc.desconto15(Double.valueOf(txtValor.getText()))));
        }else if(checkDesconto.getSelectedIndex() == 1){
            MaquinaController mc = new MaquinaController();     
            txtDesconto.setText(String.valueOf(mc.desconto30(Double.valueOf(txtValor.getText()))));
        }else if(checkDesconto.getSelectedIndex() == 2){
            MaquinaController mc = new MaquinaController();     
            txtDesconto.setText(String.valueOf(mc.desconto50(Double.valueOf(txtValor.getText()))));
        }
        }catch(NumberFormatException e){
            System.out.println(e);
        }
        
    }//GEN-LAST:event_txtValorKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> checkDesconto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMaquinas;
    private javax.swing.JTextField txtBuscaMarca;
    private javax.swing.JTextField txtBuscaModelo;
    private javax.swing.JTextField txtDesconto;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtKgs;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
