/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Geladeira;

import Controllers.GeladeiraController;
import Controllers.IdInexistenteException;
import Controllers.ValorNuloException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Mateus Bernini
 */
public class Buscar extends javax.swing.JInternalFrame {

    int id;

    /**
     * Creates new form Buscar
     */
    public Buscar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblGeladeiras = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtBuscaMarca = new javax.swing.JTextField();
        txtBuscaModelo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtQuantidade = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        txtDegelo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        checkDesconto = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txtDesconto = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        tblGeladeiras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Marca", "Modelo", "Quantidade", "Valor", "Tipo de Degelo", "desconto"
            }
        ));
        tblGeladeiras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGeladeirasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblGeladeiras);

        jLabel1.setText("Buscar pela Marca:");

        jLabel2.setText("Buscar pelo Modelo:");

        txtBuscaMarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscaMarcaKeyReleased(evt);
            }
        });

        txtBuscaModelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscaModeloKeyReleased(evt);
            }
        });

        jLabel3.setText("Id:");

        jLabel4.setText("Marca:");

        jLabel5.setText("Modelo:");

        jLabel6.setText("Quantidade");

        jLabel7.setText("Valor:");

        jLabel8.setText("Tipo de Degelo:");

        txtId.setEditable(false);
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        txtValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValorKeyReleased(evt);
            }
        });

        jLabel9.setText("Item Selecionado:");

        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setText("EXCLUIR");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnCadastrar.setText("CADASTRAR");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        jLabel10.setText("Selecione o Desconto:");

        checkDesconto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desconto de 15%", "Desconto de 30%", "Desconto de 50%", " " }));

        jLabel11.setText("Valor com desconto:");

        txtDesconto.setEditable(false);
        txtDesconto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDescontoKeyReleased(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Buscar Geladeiras");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBuscaMarca)
                            .addComponent(txtBuscaModelo, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addComponent(jLabel8)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMarca)
                            .addComponent(txtModelo)
                            .addComponent(txtQuantidade)
                            .addComponent(txtValor)
                            .addComponent(txtDegelo, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                            .addComponent(checkDesconto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDesconto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(146, 146, 146))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBuscaMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBuscaModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnExcluir)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnCadastrar)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(checkDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDegelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscaMarcaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaMarcaKeyReleased
        String busca = txtBuscaMarca.getText();
        tblGeladeiras.setModel(new GeladeiraController().geladeiraMarca(busca));
    }//GEN-LAST:event_txtBuscaMarcaKeyReleased

    private void txtBuscaModeloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaModeloKeyReleased
        String busca = txtBuscaModelo.getText();
        tblGeladeiras.setModel(new GeladeiraController().geladeiraModelo(busca));        
    }//GEN-LAST:event_txtBuscaModeloKeyReleased

    private void tblGeladeirasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGeladeirasMouseClicked
        int linha = tblGeladeiras.getSelectedRow();
        id = Integer.valueOf(tblGeladeiras.getModel().getValueAt(linha, 0).toString());
        txtId.setText(tblGeladeiras.getModel().getValueAt(linha, 0).toString());
        txtMarca.setText(tblGeladeiras.getModel().getValueAt(linha, 1).toString());
        txtModelo.setText(tblGeladeiras.getModel().getValueAt(linha, 2).toString());
        txtQuantidade.setText(tblGeladeiras.getModel().getValueAt(linha, 3).toString());
        txtValor.setText(tblGeladeiras.getModel().getValueAt(linha, 4).toString());
        txtDegelo.setText(tblGeladeiras.getModel().getValueAt(linha, 5).toString());
    }//GEN-LAST:event_tblGeladeirasMouseClicked

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        try {
            String q = txtQuantidade.getText().replace(",", ".");
            String v = txtValor.getText().replace(",", ".");
            if (new GeladeiraController().edit(txtMarca.getText(), txtModelo.getText(), Double.valueOf(q), Double.valueOf(v), txtDegelo.getText(), Double.valueOf(txtDesconto.getText()), Integer.valueOf(txtId.getText()))) {
                JOptionPane.showMessageDialog(this, "Informações editadas!!");
            }
        } catch (IdInexistenteException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            System.out.println("Erro ocorrido:" + e);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Não é permitido campos vazios!!\n Preencha todos os campos para editar!!");
            System.out.println("Erro ocorrido:" + e);
        } catch (ValorNuloException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            System.out.println("Erro ocorrido:" + e);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        try {
            if (new GeladeiraController().delete(Integer.valueOf(txtId.getText()))) {
                JOptionPane.showMessageDialog(this, "Dados da Geladeira excluídos!!");                
                txtId.setText(null);
                txtMarca.setText(null);
                txtModelo.setText(null);
                txtQuantidade.setText(null);
                txtValor.setText(null);
                txtDegelo.setText(null);
            }
            
        } catch (IdInexistenteException e) {            
            JOptionPane.showMessageDialog(this, e.getMessage());
            System.out.println("Erro ocorrido:" + e);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Campo id vazio e/ou Inexistente !!\nDigite o Id que deseja Excluir!!");
            System.out.println("Erro ocorrido:" + e);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        try {
            GeladeiraController gc = new GeladeiraController();
            String q = txtQuantidade.getText().replace(",", ".");
            String v = txtValor.getText().replace(",", ".");
            String dg = txtDesconto.getText();
            
            if (gc.create(txtMarca.getText(), txtModelo.getText(), Double.valueOf(q), Double.valueOf(v), txtDegelo.getText(), Double.valueOf(dg))) {
                JOptionPane.showMessageDialog(this, "Dados da Geladeira cadastrados!!");
            }            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Falha ao cadastrar !!\n" + "Não é permitido campos em vazio !! " + "\nNão é permitido Caracteres em valor e quantidade !!");
            System.out.println(e);
        } catch (ValorNuloException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            System.out.println("Erro ocorrido:" + e);
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void txtDescontoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescontoKeyReleased
        
    }//GEN-LAST:event_txtDescontoKeyReleased

    private void txtValorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorKeyReleased
        try{
        if( checkDesconto.getSelectedIndex() == 0){
            GeladeiraController gc = new GeladeiraController();     
            txtDesconto.setText(String.valueOf(gc.desconto15(Double.valueOf(txtValor.getText()))));
        }else if(checkDesconto.getSelectedIndex() == 1){
            GeladeiraController gc = new GeladeiraController();     
            txtDesconto.setText(String.valueOf(gc.desconto30(Double.valueOf(txtValor.getText()))));
        }else if(checkDesconto.getSelectedIndex() == 2){
            GeladeiraController gc = new GeladeiraController();     
            txtDesconto.setText(String.valueOf(gc.desconto50(Double.valueOf(txtValor.getText()))));
        }
        }catch(NumberFormatException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_txtValorKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JComboBox<String> checkDesconto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblGeladeiras;
    private javax.swing.JTextField txtBuscaMarca;
    private javax.swing.JTextField txtBuscaModelo;
    private javax.swing.JTextField txtDegelo;
    private javax.swing.JTextField txtDesconto;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
